import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import NextAuthSession from "@/components/session/next-auth-session";
import ThemeProvider from "@/components/themeProvider/theme-provider";

export const metadata: Metadata = {
  title: "Next Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='mx-auto w-11/12 md:w-10/12 antialiased'>
        <NextAuthSession>
          <ThemeProvider>
            <header className='shadow glassy'>
              <nav>
                <Navbar />
              </nav>
            </header>
            <main className='w-full min-h-[75dvh]'>{children}</main>
            <footer className='shadow glassy'>Footer</footer>
          </ThemeProvider>
        </NextAuthSession>
      </body>
    </html>
  );
}
